version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - run:
          name: Code lint
          command: make lint

  python-tests:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - run:
          name: Test
          command: make test

  archive-build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build archive
          command: make zip

workflows:
  version: 2
  main:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/

      - python-tests:
          filters:
            tags:
              only: /.*/

      - archive-build:
          filters:
            tags:
              only: /.*/
